### ISSUE TITLE
Breadcrumb are "too big"

### ISSUE THREAD

**Issue by deajan** [rauenzi/Trilium-Breadcrumbs#6]
I know this maybe out of scope of your breadcrumbs plugin, but since I use it, I noticed that breadcrums becore too big in my case:

![image](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/4681318/38aa4f3e-b61d-4d9b-ac52-590159549738)

Any way to reduce the font size / cut name at n letters ?

**Comment by zerebos** [comment]
You can definitely do that with some CSS, here's an example:

```css
#breadcrumbs span a {
    white-space: pre;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: 300px;
    display: inherit;
}
```

and adjust the width to your liking. 


I'll leave this issue open as it might be a good idea to make this a toggle or something in the addon itself
